services:

  test_elasticsearch:
    image: elasticsearch:7.8.0
    container_name: test_elasticsearch
    environment:
      - node.name=test_elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=test_elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - test_network

  test_meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: test_meilisearch
    ports:
      - "7700:7700"
    networks:
      - test_network
    environment:
      MEILISEARCH_MASTER_KEY: test_master_key
      MEILISEARCH_URL: http://localhost:7700
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 2s
      timeout: 1s
      retries: 10

version: '3.8'

volumes:
  data01:
    driver: local

networks:
  test_network:
    name: test_network
    driver: bridge
    external: true
