name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        toxenv: [django42, django52, quality]

    env:
      MEILISEARCH_URL: http://localhost:7700

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: setup python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start Meilisearch
      run: make meili-up

    - name: Start Elasticsearch
      run: make elastic-up

    - name: Install pip and pip-tools
      run: pip install -r requirements/pip-tools.txt

    - name: Install Dependencies
      run: |
        pip install setuptools
        pip install -r requirements/ci.txt

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      # Sleep is needed to give elasticsearch enough time to startup.
      # Longer term we should switch to the upstream ES github action to start up the server
      run: sleep 10 && tox

    - name: Run Coverage
      if: matrix.python-version == '3.12' && matrix.toxenv=='django52'
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
